### ISSUE TITLE
Dragging and dropping images can make the editor freeze

### ISSUE THREAD

**Issue by dae** [ankitects/help-wanted#17]
A video demonstrating the problem is here:

https://forums.ankiweb.net/t/crashing-anki-version-2-1-29-bbff62bf/1650/5

**Comment by ANH25** [comment]
After some experimentation, I've found that the freeze can be eliminated by explicitly handling `dragEnterEvent` in EditorWebView, like this:
```python
def dragEnterEvent(self, evt):
  evt.accept()
```
But this prevents the fields from receiving the dragover event, as a result, the `onDragOver` function in editor.ts is never called.
The issue does not seem to be caused by anything in editor.ts. merely handling `dragEnterEvent` fixes it, but introduces another problem.

**Comment by dae** [comment]
Thanks for digging into it, I'll have another play with it when I have a chance

**Comment by ANH25** [comment]
It seems that the dragover JavaScript event is triggered in the default dragEnterEvent handler of QWebEngineView.
The following causes the dragover event to be fired as usual but reintroduces the freeze:

```python
def dragEnterEvent(self, evt):
    super().dragEnterEvent(evt)
```

Doing something similar in dropEvent eliminates the freeze:

```python
def dropEvent(self, evt):
    super().dropEvent(evt)
```
But this brings with it the default handling of drop events in addtion to Anki's handling (e.g. dropped images will be opened *and* copied to fields).

The whole thing can be reproduced outside Anki (as in [this example](https://gist.github.com/ANH25/973866ffa8d3499ebb9593354d8abcce)).
I think this is ultimately a QT bug. I guess it would be more reasonable that JavaScript events fire regardless of custom QT event handlers.

**Comment by ANH25** [comment]
I've found a workaround:
https://github.com/ANH25/anki/commit/c46aaa037bc1aa2b878163a004b0b128a153a568

Please let me know if it's any good.

**Comment by dae** [comment]
Thanks ANH - I didn't notice any problems, and it seems to work well here. I'm sure this will make a bunch of users happy!

Merged in https://github.com/ankitects/anki/pull/738
