### ISSUE TITLE
Add-on to ignore accents by default

### ISSUE THREAD

**Issue by dae** [ankitects/help-wanted#8]
Some users frequently search for accented text, and want to be able to type "foo" instead of "nc:foo" (https://anki.tenderapp.com/discussions/ankidesktop/41875-proposal-card-browser-search-change-default-search-behaviour-in-respect-to-accents-nc-syntax-as-default). This should be simple to implement in an add-on. In the master branch, the browser_will_search hook can be used to alter the search text, so implementing this is probably just a case of splitting ctx.search on whitespace, prepending substrings that don't have a ':' character, and then joining the substrings back into a single string.

Please note that ctx.search was ignored in earlier versions, so you'll need to test with the current master branch

**Comment by hssm** [comment]
I've updated the [existing add-on](https://ankiweb.net/shared/info/1924690148) to do just that. However, it is only available for 2.1.28+.

**Comment by itsdomme** [comment]
That's great! But, when do we get 2.1.28 stable?

**Comment by dae** [comment]
Thanks Houssam.

.28 is still in alpha and will take some time to stabilise. If this is an important issue for you, you can always use an older Anki version and the old add-on.
